<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Alias plugin
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.moodle.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   local_alias
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'Manage Aliases';
$string['managealias'] = 'Manage Alias';
$string['friendly'] = 'Friendly';
$string['destination'] = 'Destination';
$string['defaultfriendly'] = 'Please enter friendly';
$string['defaultdestination'] = 'Please enter destination';
$string['messagecancelled'] = 'You cancelled the alias form!';
$string['messagecreated'] = 'You created the alias with Friendly field';
$string['messageupdated'] = 'You updated the alias with Friendly field';
$string['messagefilter'] = 'You filtered the alias with a Friendly field';
$string['modaldeletetitle'] = 'You created the alias form with Friendly';
$string['messagefilter'] = ' has just been filtered';
$string['messagedeletefail'] = 'Delete fail!';
$string['alias:managealias'] = 'Manage Alias';
$string['filterfriendly'] = 'Filter Friendly';
$string['filter'] = 'Go';
$string['editalias'] = 'Edit Alias';
